name: WTA Connect - Build and Analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and analyze WTA Connect
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Check project structure
        run: |
          echo "=== Current Directory ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la
          echo "=== Xcode Project Search ==="
          find . -name "*.xcodeproj" -type d
          if [ -d "wtaconnect.xcodeproj" ]; then
            echo "=== Project Structure ==="
            ls -R wtaconnect.xcodeproj
            echo "=== Project File Contents ==="
            cat wtaconnect.xcodeproj/project.pbxproj || echo "Cannot read project file"
          else
            echo "Project file not found"
            exit 1
          fi

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Create new Xcode project
        if: ${{ failure() }}
        run: |
          xcodebuild -create \
            -template "Single View App" \
            -destination . \
            -project wtaconnect.xcodeproj \
            -target wtaconnect \
            -bundleID "com.wta.wtaconnect" \
            -allowProvisioningUpdates

      - name: Build and Analyze
        run: |
          # Trouver le scheme automatiquement
          SCHEME=$(ls wtaconnect.xcodeproj/xcshareddata/xcschemes/*.xcscheme 2>/dev/null | head -n 1 | sed 's/.*\/\(.*\)\.xcscheme/\1/')
          if [ -z "$SCHEME" ]; then
            SCHEME="wtaconnect"
          fi
          echo "Using scheme: $SCHEME"
          
          xcodebuild clean build analyze \
            -scheme "$SCHEME" \
            -project "wtaconnect.xcodeproj" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Debug \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build.log | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: build.log

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/
            *.ipa
            *.app 
