name: WTA Connect - Build and Analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and analyze WTA Connect
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Show build settings
        run: |
          echo "=== Current Directory ==="
          pwd
          echo "=== Project Structure ==="
          ls -R
          echo "=== Xcode Project Info ==="
          xcodebuild -list -project wtaconnect.xcodeproj || true

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project wtaconnect.xcodeproj \
            -scheme wtaconnect \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Debug \
            -enableCodeCoverage YES \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | tee build.log | xcpretty --color --simple && exit ${PIPESTATUS[0]}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            build.log
            *.xcresult

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/
            *.ipa
            *.app 
